"""change table 2

Revision ID: 3928f46cc434
Revises: 7bd251522e82
Create Date: 2024-10-08 13:00:56.004303

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "3928f46cc434"
down_revision: Union[str, None] = "7bd251522e82"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tournament_player",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("id_player", sa.Integer(), nullable=False),
        sa.Column("id_tournament_team", sa.Integer(), nullable=False),
        sa.Column(
            "created_on",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_on",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["id_player"], ["player.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["id_tournament_team"], ["tournament_team.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "id_player", "id_tournament_team", name="tournament_player_uc"
        ),
    )
    op.drop_constraint(
        "tournament_team_id_player_fkey", "tournament_team", type_="foreignkey"
    )
    op.drop_column("tournament_team", "id_player")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "tournament_team",
        sa.Column(
            "id_player", sa.INTEGER(), autoincrement=False, nullable=True
        ),
    )
    op.create_foreign_key(
        "tournament_team_id_player_fkey",
        "tournament_team",
        "player",
        ["id_player"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_table("tournament_player")
    # ### end Alembic commands ###
