"""change table, add table

Revision ID: 6f21cd380a34
Revises: 471c7df07642
Create Date: 2024-10-04 12:50:34.876501

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "6f21cd380a34"
down_revision: Union[str, None] = "471c7df07642"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "role",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name_role", sa.String(length=50), nullable=False),
        sa.Column(
            "created_on",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_on",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name_role"),
    )
    op.create_table(
        "player_team",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("id_player", sa.Integer(), nullable=False),
        sa.Column("id_team", sa.Integer(), nullable=False),
        sa.Column(
            "created_on",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_on",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["id_player"], ["player.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["id_team"], ["team.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id_player", "id_team", name="player_team_uc"),
    )
    op.add_column("player", sa.Column("role", sa.Integer(), nullable=False))
    op.drop_constraint("player_uc", "player", type_="unique")
    op.create_unique_constraint(
        "player_uc",
        "player",
        ["first_name", "last_name", "patronymic", "role"],
    )
    op.drop_constraint("player_id_team_fkey", "player", type_="foreignkey")
    op.create_foreign_key(
        None, "player", "role", ["role"], ["id"], ondelete="CASCADE"
    )
    op.drop_column("player", "id_team")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "player",
        sa.Column(
            "id_team", sa.INTEGER(), autoincrement=False, nullable=False
        ),
    )
    op.drop_constraint(None, "player", type_="foreignkey")
    op.create_foreign_key(
        "player_id_team_fkey",
        "player",
        "team",
        ["id_team"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint("player_uc", "player", type_="unique")
    op.create_unique_constraint(
        "player_uc",
        "player",
        ["first_name", "last_name", "patronymic", "id_team"],
    )
    op.drop_column("player", "role")
    op.drop_table("player_team")
    op.drop_table("role")
    # ### end Alembic commands ###
