"""change table tournament_team, delete table player_team

Revision ID: 7bd251522e82
Revises: d93407d87058
Create Date: 2024-10-08 12:38:26.209033

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "7bd251522e82"
down_revision: Union[str, None] = "d93407d87058"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("player_team")
    op.add_column(
        "tournament_team", sa.Column("id_player", sa.Integer(), nullable=False)
    )
    op.create_foreign_key(
        None,
        "tournament_team",
        "player",
        ["id_player"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "tournament_team", type_="foreignkey")
    op.drop_column("tournament_team", "id_player")
    op.create_table(
        "player_team",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column(
            "id_player", sa.INTEGER(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "id_team", sa.INTEGER(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "created_on",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated_on",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["id_player"],
            ["player.id"],
            name="player_team_id_player_fkey",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["id_team"],
            ["team.id"],
            name="player_team_id_team_fkey",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name="player_team_pkey"),
        sa.UniqueConstraint("id_player", "id_team", name="player_team_uc"),
    )
    # ### end Alembic commands ###
