"""add column date in table game

Revision ID: 8d1a48534875
Revises: a5b130b23bd7
Create Date: 2024-12-04 12:13:55.662938

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8d1a48534875"
down_revision: Union[str, None] = "a5b130b23bd7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("game", sa.Column("date_game", sa.Date(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("game", "date_game")
    # ### end Alembic commands ###
