"""change table Stat

Revision ID: 96cc8fac3f24
Revises: de2d84ee8533
Create Date: 2024-10-08 14:45:00.709645

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "96cc8fac3f24"
down_revision: Union[str, None] = "de2d84ee8533"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "stat",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("id_parameter", sa.Integer(), nullable=False),
        sa.Column("accuracy", sa.Boolean(), nullable=False),
        sa.Column("result", sa.Boolean(), nullable=True),
        sa.Column("id_player", sa.Integer(), nullable=False),
        sa.Column("id_assistant", sa.Integer(), nullable=False),
        sa.Column(
            "created_on",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_on",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["id_assistant"], ["tournament_player.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["id_parameter"], ["parameter.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["id_player"], ["tournament_player.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_table("player_parameter")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "player_parameter",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column(
            "id_player", sa.INTEGER(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "id_parameter", sa.INTEGER(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "id_team", sa.INTEGER(), autoincrement=False, nullable=False
        ),
        sa.Column("count", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "created_on",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated_on",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["id_parameter"],
            ["parameter.id"],
            name="player_parameter_id_parameter_fkey",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["id_player"],
            ["player.id"],
            name="player_parameter_id_player_fkey",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["id_team"],
            ["team.id"],
            name="player_parameter_id_team_fkey",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name="player_parameter_pkey"),
        sa.UniqueConstraint(
            "id_player", "id_parameter", "id_team", name="player_parameter_uc"
        ),
    )
    op.drop_table("stat")
    # ### end Alembic commands ###
