"""add table player column birth

Revision ID: d93407d87058
Revises: b24449f15440
Create Date: 2024-10-07 16:56:09.225308

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d93407d87058"
down_revision: Union[str, None] = "b24449f15440"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("player", sa.Column("birth", sa.Date(), nullable=False))
    op.drop_constraint("player_uc", "player", type_="unique")
    op.create_unique_constraint(
        "player_uc",
        "player",
        ["first_name", "last_name", "patronymic", "birth", "id_role"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("player_uc", "player", type_="unique")
    op.create_unique_constraint(
        "player_uc",
        "player",
        ["first_name", "last_name", "patronymic", "id_role"],
    )
    op.drop_column("player", "birth")
    # ### end Alembic commands ###
